# Athena test configuration example

# Global parameters (applied to all tests unless overridden)
parameters:
  timeout: 30 # Default timeout in seconds for all tests
  retry_count: 2 # Number of retries for failed tests
  environment: "production"
  log_level: "info"

# List of tests to run with their specific parameters
tests:
  # Legacy plugin-based tests
  - name: "system"
    parameters:
      collect_network: true # Enable network information collection

  # Direct protocol-based tests
  - name: "memory"
    parameters:
      threshold: 80 # Memory usage threshold percentage
      warning_level: 60 # Warning level percentage

  - name: "disk"
    parameters:
      path: "/tmp"
      threshold: 90 # Disk usage threshold percentage

  # More examples of using protocol-based tests with different parameters
  - name: "disk"
    parameters:
      path: "/"
      threshold: 95 # Different threshold for root filesystem
