# Athena test configuration example

# Global parameters
parameters:
  timeout: 30 # Default timeout in seconds for all tests
  retry_count: 2 # Number of retries for failed tests
  environment: "production"
  log_level: "info"

# List of tests to run with their specific parameters
tests:
  - name: "system"
    parameters:
      collect_network: true # Enable network information collection

  - name: "system"
    parameters:
      memory:
        threshold: 10 # Override the default memory threshold (80%)

  - name: "system"
    parameters:
      disk:
        path: "/tmp"
        threshold: 5 # Override the default disk threshold (90%)

reports:
  - name: "json"
