# Athena test configuration example

# Global parameters (applied to all tests unless overridden)
parameters:
  timeout: 30 # Default timeout in seconds for all tests
  retry_count: 2 # Number of retries for failed tests
  environment: "production"
  log_level: "info"

# Test execution strategy
execution_strategy: "parallel" # Options: sequential, parallel
# max_workers: 4  # Optional: number of workers for parallel execution

# List of tests to run with their specific parameters
tests:
  - name: "system"
    parameters:
      collect_network: true # Enable network information collection

  - name: "system"
    parameters:
      memory:
        threshold: 10 # Override the default memory threshold (80%)

  - name: "system"
    parameters:
      disk:
        path: "/tmp"
        threshold: 5 # Override the default disk threshold (90%)
