# Athena test configuration example

# Global parameters (applied to all tests unless overridden)
timeout: 30 # Default timeout in seconds for all tests
retry_count: 2 # Number of retries for failed tests

# List of tests to run with their specific parameters
tests:
  - name: system_info
    parameters:
      collect_network: true # Enable network information collection

  - name: memory_check
    parameters:
      memory_threshold: 75 # Override the default memory threshold (90%)

# You can add more global parameters here
environment: "production"
log_level: "info"
