# Athena test configuration example

# Global parameters
parameters:
  timeout: 30 # Default timeout in seconds for all tests
  retry_count: 2 # Number of retries for failed tests
  environment: "production"
  log_level: "info"

# List of tests to run with their specific parameters
tests:
  - name: "Network collection test"
    plugin_identifier: "system"
    parameters:
      collect_network: true

  - name: "Memory test"
    plugin_identifier: "system"
    parameters:
      memory:
        threshold: 10

  - name: "Disk test"
    plugin_identifier: "system"
    parameters:
      disk:
        path: "/tmp"
        threshold: 5

reports:
  - name: "rich_console"
    plugin_identifier: "rich_console"
    parameters:
      format: "table"
